name: corsac_state
version: 0.1.0-dev
description: Generate Map snapshots of Dart object's state.
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/corsac-dart/state

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  intl: "^0.12.7"

dev_dependencies:
  test: "^0.12.4+7"
  dart_coveralls: "^0.4.0"
